### ISSUE TITLE
AttributeError: 'Sequential' object has no attribute '_compile_time_distribution_strategy'

### ISSUE THREAD

**Issue by j-beaver** [nicknochnack/OpenAI-Reinforcement-Learning-with-Custom-Environment#1]
Thanks much Nicholas for this nice tutorial
There is an issue I'm facing:

Getting "AttributeError: 'Sequential' object has no attribute '_compile_time_distribution_strategy'" error on "dqn.compile(Adam(lr=1e-3), metrics=['mae'])" opertaion

Traceback (most recent call last):
  File "C:/Users/Alex/PycharmProjects/Lamp/example.py", line 94, in <module>
    dqn.compile(Adam(lr=1e-3), metrics=['mae'])
  File "C:\Users\Alex\.conda\envs\deeplearning\lib\site-packages\rl\agents\dqn.py", line 168, in compile
    self.target_model = clone_model(self.model, self.custom_model_objects)
  File "C:\Users\Alex\.conda\envs\deeplearning\lib\site-packages\rl\util.py", line 16, in clone_model
    clone.set_weights(model.get_weights())
  File "C:\Users\Alex\.conda\envs\deeplearning\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 179, in get_weights
    self._compile_time_distribution_strategy)
AttributeError: 'Sequential' object has no attribute '_compile_time_distribution_strategy'

Here is the full code:
```

from gym import Env
from gym.spaces import Discrete, Box
import numpy as np
import random


class ShowerEnv(Env):
    def __init__(self):
        # Actions we can take, down, stay, up
        self.action_space = Discrete(3)
        # Temperature array
        self.observation_space = Box(low=np.array([0]), high=np.array([100]))
        # Set start temp
        self.state = 38 + random.randint(-3, 3)
        # Set shower length
        self.shower_length = 60

    def step(self, action):
        # Apply action
        # 0 -1 = -1 temperature
        # 1 -1 = 0
        # 2 -1 = 1 temperature
        self.state += action - 1
        # Reduce shower length by 1 second
        self.shower_length -= 1

        # Calculate reward
        if self.state >= 37 and self.state <= 39:
            reward = 1
        else:
            reward = -1

            # Check if shower is done
        if self.shower_length <= 0:
            done = True
        else:
            done = False

        # Apply temperature noise
        # self.state += random.randint(-1,1)
        # Set placeholder for info
        info = {}

        # Return step information
        return self.state, reward, done, info

    def render(self):
        # Implement viz
        pass

    def reset(self):
        # Reset shower temperature
        self.state = 38 + random.randint(-3, 3)
        # Reset shower time
        self.shower_length = 60
        return self.state



import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam

env = ShowerEnv()

states = env.observation_space.shape
actions = env.action_space.n

def build_model(states, actions):
    model = Sequential()
    model.add(Dense(24, activation='relu', input_shape=states))
    model.add(Dense(24, activation='relu'))
    model.add(Dense(actions, activation='linear'))
    return model

model = build_model(states, actions)
model.summary()

from rl.agents import DQNAgent
from rl.policy import BoltzmannQPolicy
from rl.memory import SequentialMemory



def build_agent(model, actions):
    policy = BoltzmannQPolicy()
    memory = SequentialMemory(limit=50000, window_length=1)
    dqn = DQNAgent(model=model, memory=memory, policy=policy,
                  nb_actions=actions, nb_steps_warmup=10, target_model_update=1e-2)
    return dqn

dqn = build_agent(model, actions)
dqn.compile(Adam(lr=1e-3), metrics=['mae'])
```

**Comment by j-beaver** [comment]
what I found is model deletion at line #64 of your original code doesn't work because it is not build yet
though my issue was fixed when I place  model deletion after model build and then build model again after imports from rl.*

```
def build_model(states, actions):
    model = Sequential()
    model.add(Dense(24, activation='relu', input_shape=states))
    model.add(Dense(24, activation='relu'))
    model.add(Dense(actions, activation='linear'))
    return model

model = build_model(states, actions)
model.summary()

del model

from rl.agents import DQNAgent
from rl.policy import BoltzmannQPolicy
from rl.memory import SequentialMemory

model = build_model(states, actions)

```
